# Generated by Django 6.1.1 on 2026-09-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagenes_secundarias',
            field=models.TextField(blank=True, help_text='URLs de imágenes secundarias/galería separadas por salto de línea'),
        ),
    ]
