# Generated by Django 6.1.1 on 2026-09-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_producto_imagenes_secundarias'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_tachado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio anterior antes del descuento', max_digits=10, null=True, verbose_name='Precio Normal Tachado (S/.)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Oferta (S/.)'),
        ),
    ]
