# Generated by Django 6.1.1 on 2026-09-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_producto_precio_tachado_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_url',
            field=models.CharField(blank=True, help_text='URL de imagen externa, ruta /media/... o /static/...', max_length=500),
        ),
    ]
