# Generated by Django 6.1.1 on 2026-09-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_producto_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='almacenamiento',
            field=models.CharField(blank=True, help_text='Ej: 512GB SSD M.2 NVMe PCIe 4.0', max_length=150, verbose_name='Almacenamiento'),
        ),
        migrations.AddField(
            model_name='producto',
            name='especificaciones_adicionales',
            field=models.TextField(blank=True, help_text="Una especificación por línea en formato 'Característica: Detalle' (ej: Teclado: Español con pad numérico)", verbose_name='Especificaciones Adicionales (Clave: Valor)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado_producto',
            field=models.CharField(blank=True, default='Nuevo Sellado', help_text='Ej: Nuevo Sellado, Reacondicionado Certificado', max_length=50, verbose_name='Condición / Estado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='garantia',
            field=models.CharField(blank=True, default='12 Meses Oficial en tienda Caraz', max_length=150, verbose_name='Garantía'),
        ),
        migrations.AddField(
            model_name='producto',
            name='grafica',
            field=models.CharField(blank=True, help_text='Ej: NVIDIA RTX 3050 6GB / AMD Radeon 610M / Intel Iris Xe', max_length=150, verbose_name='Tarjeta de Video / Gráficos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, help_text='Ej: Lenovo, HP, ASUS, Kingston, Logitech', max_length=100, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo_codigo',
            field=models.CharField(blank=True, help_text='Ej: 82YU017LLM, 15-fc0225dx', max_length=150, verbose_name='Modelo / Código de Parte'),
        ),
        migrations.AddField(
            model_name='producto',
            name='pantalla',
            field=models.CharField(blank=True, help_text='Ej: 15.6" FHD (1920x1080) Antirreflejo IPS', max_length=150, verbose_name='Pantalla'),
        ),
        migrations.AddField(
            model_name='producto',
            name='procesador',
            field=models.CharField(blank=True, help_text='Ej: Intel Core i5-13420H / AMD Ryzen 5 7520U', max_length=200, verbose_name='Procesador'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ram',
            field=models.CharField(blank=True, help_text='Ej: 16GB DDR5 5200MHz / 8GB LPDDR5', max_length=100, verbose_name='Memoria RAM'),
        ),
    ]
