# Generated by Django 6.1.1 on 2026-10-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_agregar_categoria_televisores'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='url_origen',
            field=models.CharField(blank=True, help_text='Enlace web original desde donde se importó el producto (Infotec)', max_length=600, null=True, verbose_name='Enlace de Origen / Infotec'),
        ),
    ]
